version: '3.9'

services:
  time:
    image: tangramor/nginx-php8-fpm:php8.4.3_withoutNodejs
    restart: always
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.time.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.time.entrypoints=websecure"
      - "traefik.http.routers.time.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    name: web
    external: true
